In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.4'

In [9]:
x = np.array([1,2,3,4])

# //cada lista é uma linha
matriz = np.array([[1,2,3],[4,5,6]],dtype=np.int32)

print(matriz)
print(type(matriz))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
matrizErrada = np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [14]:
## dimensão de um objeto
matriz.shape 

m,n = matriz.shape

print(matriz)
print(m,n)
print(type(matriz.shape))

## acesando indices
print((matriz.shape[0]))
print((matriz.shape[1]))

[[1 2 3]
 [4 5 6]]
2 3
<class 'tuple'>
2
3


In [ ]:
##AULA 2

In [17]:
x= np.array([])


## array padrão é d tipo float64
print(x)
print(x.dtype)


[]
float64


In [19]:
y = np.array([1,2,3,4])

#array 1D
print(y.shape)

#padrão é int64 para array 1
print(y.dtype)

(4,)
int64


In [ ]:
#transposição de um array

In [20]:
print("transporta de y", y.T)

transporta de y [1 2 3 4]


In [24]:
A = np.array([[1,2,3],[4,5,6]])

print(A)

print("transposta:")
print(A.T)

[[1 2 3]
 [4 5 6]]
transposta:
[[1 4]
 [2 5]
 [3 6]]


In [25]:
#tipos de array:

#modificando o tipo do array
x = np.array([1,2,3],dtype=np.int32) 
y = np.array([1,2,3],dtype=np.float32) 
z = np.array([1,2,3],dtype=np.complex128) 

print(x)
print(y)
print(z)

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [26]:

## no int64 não aparece a especificacao de tipo pq é o padrão 
x2 = np.array([1,2,3],dtype=np.int64) 

x2

array([1, 2, 3])

In [27]:
## ja o x mostra o dtype=int32 pq foge do padrão
x

array([1, 2, 3], dtype=int32)

In [32]:
x = np.array([1,2,3],dtype=np.int32) 
print(x.dtype)

#só altera se tiver igualdade
x = x.astype(np.float64)
print(x.dtype)

int32
float64


In [38]:
# erros com dimensão:

# X é array de 1D, vai dar erro pq n tem o N
print("numero de dimenssão: ",x.ndim)
m,n = x.shape




numero de dimenssão:  1


ValueError: not enough values to unpack (expected 2, got 1)

In [39]:
#esse tipo de  verificacao previne erros futuros em solucoes mais complexas
if(x.ndim > 1):
    m,n = x.shape
    print("dimenssoes 2D : ", m,n)
else:
    n = x.shape
    print("dimenssoes 1D : ",n)

dimenssoes 1D :  (3,)
