#Tipos de Arrays no Numpy

In [2]:
import numpy as np

x = np.array([1,2,3,4,5], dtype=np.int32)
x2 = np.array([1,2,3,4,5], dtype=np.float32)
x3 = np.array([1,2,3,4,5], dtype=np.complex64)

In [3]:
print(x)
print(x2)
print(x3)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# Alterando os tipos

In [7]:
print(x2.dtype)

print(x2.astype(np.float128))

print(x2.dtype)
x2 = x2.astype(np.float128)

print(x2.dtype)

float32
[1. 2. 3. 4. 5.]
float32
float128


# Erro obter dimensões