# Exercicio 1 - avaliar a igualdade de vetores e seus elementos


- A partir de dois vetores x e y 
- construir uma função para avaliar a igualdade
- apresentar os elementos iguais dos vetores
- apresentar os indices onde os alementos são iguais nos dois vetores



In [2]:
import numpy as np

In [3]:
x = np.array([1.2,2,1,4,3,5.5,2,7,8,9,10])
y = np.array([1,2,1.3,4,3,5,2,7,8,9,10])

In [6]:
cmp  = x == y
print(cmp)

[False  True False  True  True False  True  True  True  True  True]


In [14]:

print(np.where(y==x))

(array([ 1,  3,  4,  6,  7,  8,  9, 10]),)


In [5]:
i = 0

if(cmp.all()):
    print("Todos os valores são iguais.")
elif(cmp.any()):
    print("Alguns valores são iguais.")

    for e in cmp:
        if(e):
            print("%.1f"% y[i])
        i += 1
    
    print('------------')

    for e in x:
        j = np.where( e == y) # indexação igual
        print(j)
        if (j[0].size != 0):
            print(y[j])
else:
    print("Todos os elementos são diferentes")





Alguns valores são iguais.
2.0
4.0
3.0
2.0
7.0
8.0
9.0
10.0
------------
(array([], dtype=int64),)
(array([1, 6]),)
[2. 2.]
(array([0]),)
[1.]
(array([3]),)
[4.]
(array([4]),)
[3.]
(array([], dtype=int64),)
(array([1, 6]),)
[2. 2.]
(array([7]),)
[7.]
(array([8]),)
[8.]
(array([9]),)
[9.]
(array([10]),)
[10.]
