# Indexing e Slicing

indexação e fatiamento de arrays

In [2]:
import numpy as np

In [3]:
x = np.array([1.2,1.4,3.,5.2,7.7])

In [5]:
a = x[0] #pegando primeiro elemento

b = x[-1] #pegando ultimo elemento

print(a)
print(b)

1.2
7.7


In [6]:
x[1:3] #fatiando do index  1 até 3

#note que o terceiro elemento não entra

array([1.4, 3. ])

In [7]:
x[-2:]

array([5.2, 7.7])

In [8]:
x[2:]

array([3. , 5.2, 7.7])

In [11]:
#diferenciacao entre as estuturas

#mesmos valores, estruturas diferentes

t1 = x[2:3]
t2 = x[2]

print(t1)
print(t2)

print(type(t1)) #array

print(type(t2)) #numero

[3.]
3.0
<class 'numpy.ndarray'>
<class 'numpy.float64'>
