In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.4'

In [9]:
x = np.array([1,2,3,4])

# //cada lista é uma linha
matriz = np.array([[1,2,3],[4,5,6]],dtype=np.int32)

print(matriz)
print(type(matriz))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
matrizErrada = np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [14]:
## dimensão de um objeto
matriz.shape 

m,n = matriz.shape

print(matriz)
print(m,n)
print(type(matriz.shape))

## acesando indices
print((matriz.shape[0]))
print((matriz.shape[1]))

[[1 2 3]
 [4 5 6]]
2 3
<class 'tuple'>
2
3
