In [1]:
import numpy as np

In [2]:
y = np.array([1,2,3])
y.shape

#Array 1D
y.dtype

dtype('int64')

In [3]:
y.T

#fundamentalmente a transporta são iguais na lib do python

array([1, 2, 3])

In [5]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])