##Organizando em tuplas os indices

In [3]:
import numpy as np 


#gerando numeros aleatórios
## definindo o seed

np.random.seed(777)

##gerando uma matriz de numeros aleatórios, os os numeros varias até 100 e o tamanho 3,3
x = np.random.randint(100,size=(3,3))
print(x)


[[47 59 38]
 [87 49 71]
 [29 39 89]]


In [4]:
linha, coluna = np.where( ( x >= 40) & (x<= 50))
valores = x[linha,coluna]
print(valores)



[47 49]


## usando a funcao .where() para substuir todos que n passam no filtro por zero
#onde tudo que passar pelo critério vira viraraá o prmeiro parametro, no caso X
#oque não passar vira 0

In [11]:
a = np.where(((x >= 40) & (x<= 50)),x,0)
print(a)





[[47  0  0]
 [ 0 49  0]
 [ 0  0  0]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0  0]]


In [12]:
a = np.where(((x >= 40) & (x<= 50)),10,0)
print(a)

[[10  0  0]
 [ 0 10  0]
 [ 0  0  0]]


In [13]:
##utilizando a negacao
a = np.where(~((x >= 40) & (x<= 50)),10,x)
print(a)

[[47 10 10]
 [10 49 10]
 [10 10 10]]
