##gerando matrizes apatir de numeros aleatórios 
#seed = ponto de partida para gerar o numero

In [2]:
import numpy as np 


#gerando numeros aleatórios
## definindo o seed

np.random.seed(777)

##gerando uma matriz de numeros aleatórios, os os numeros varias até 100 e o tamanho 3,3
x = np.random.randint(100,size=(3,3))
print(x)



array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [3]:
##gerando uma matriz binária  4x4
#OBS randint indica que será um numero randomico e inteiro.
x = np.random.randint(2,size=(4,4))
print(x)


[[0 0 0 1]
 [0 1 0 0]
 [1 1 0 0]
 [1 1 1 1]]
