##Organizando em tuplas os indices

In [1]:
import numpy as np 


#gerando numeros aleatórios
## definindo o seed

np.random.seed(777)

##gerando uma matriz de numeros aleatórios, os os numeros varias até 100 e o tamanho 3,3
x = np.random.randint(100,size=(3,3))
print(x)


[[47 59 38]
 [87 49 71]
 [29 39 89]]


In [4]:
A = np.where( ( x >= 40) & (x<= 80),x,0)
##criando A como submatriz
print(A)



[[47 59  0]
 [ 0 49 71]
 [ 0  0  0]]


In [6]:
##modificando apenas 2 valores da nova matriz A

A[1:3,0]= 9,9
print(A)
print("---------------")
print(x)

[[47 59  0]
 [ 9 49 71]
 [ 9  0  0]]
---------------
[[47 59 38]
 [87 49 71]
 [29 39 89]]


##perceba que nesse caso não ocorre broadcasting dos valores

In [7]:
x[1:3,0]= 99,99
print(A)
print("---------------")
print(x)

[[47 59  0]
 [ 9 49 71]
 [ 9  0  0]]
---------------
[[47 59 38]
 [99 49 71]
 [99 39 89]]
