##Organizando em tuplas os indices

In [1]:
import numpy as np 


#gerando numeros aleatórios
## definindo o seed

np.random.seed(777)

##gerando uma matriz de numeros aleatórios, os os numeros varias até 100 e o tamanho 3,3
x = np.random.randint(100,size=(3,3))
print(x)


[[47 59 38]
 [87 49 71]
 [29 39 89]]


In [2]:
linha, coluna = np.where( ( x >= 40) & (x<= 50))

###para saber quais são esses valores temos:
valores = x[linha,coluna]
print("valores:", valores)

valores: [47 49]


In [5]:
##utilizando o zip para junar
lista = zip(linha,coluna)
print(lista)

##transformando em uma lista
lista = list(lista)
print(lista) ## agora temos o conjunto de indices que passam pelo filtro


[(0, 0), (1, 1)]


##Note: uma vez como tupla é possivel realizar varios tipos de manipulações

In [6]:
##Utilizando list comprehention para listar
[x[i] for i in lista ]

[47, 49]