##Clonando vetores

# usando o comando _like para clonar vetores em termos de alocação de memoria

In [7]:
import numpy as np

x = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9],np.float128)

In [11]:
h = np.empty_like(x)
h

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float128)

In [9]:
h = np.zeros_like(x)
h

array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float128)

In [10]:
h = np.ones_like(x)
h

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float128)