## Utilizando .hsplit() para matrizes

In [2]:
import numpy as np 

x = np.arange(24).reshape(4,6) ## 4*6 = 24
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
## [ 2, 4 ]  
## 2 elementos vertical
## 4 linhas
x1,x2,x3 =  np.hsplit(x,[2,4]) 

In [5]:
print(x,'\n')
print(x1,'\n')
print(x2,'\n')
print(x3,'\n')


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] 

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] 

[[ 4  5]
 [10 11]
 [16 17]
 [22 23]] 

