## Trabalhando com técnicas avançadas de manipulação de Arrays 2D ou Matrizes

In [2]:
import numpy as np 

np.random.seed(555)

## funcao RAND() gera numeros aleatórios entre 0 - 1
x = np.random.rand(3,3)
x

array([[0.71783409, 0.04785513, 0.94447198],
       [0.68638004, 0.58120733, 0.14267862],
       [0.94591918, 0.33999059, 0.62043546]])

In [4]:
y = x.copy() + 1
y

array([[1.71783409, 1.04785513, 1.94447198],
       [1.68638004, 1.58120733, 1.14267862],
       [1.94591918, 1.33999059, 1.62043546]])

In [6]:
z = y[:,2].copy(); z

array([1.94447198, 1.14267862, 1.62043546])

## criando uma matriz atráves do stackamento de um vetor utilizando VSTACK

In [12]:
print(z)
print("----------------")
print(np.vstack([z,z,z,z])) ## 4 colunas do mesmo vetor Z
print("----------------")
print(np.vstack([z,z])) ## 4 colunas do mesmo vetor Z

[1.94447198 1.14267862 1.62043546]
----------------
[[1.94447198 1.14267862 1.62043546]
 [1.94447198 1.14267862 1.62043546]
 [1.94447198 1.14267862 1.62043546]
 [1.94447198 1.14267862 1.62043546]]
----------------
[[1.94447198 1.14267862 1.62043546]
 [1.94447198 1.14267862 1.62043546]]
