## utilizando vsplit para splitar a matrizes verticalmente;

# para vsplit(x,[i])
x = matriz splitada
i = indice da linha 

tudo que tiver antes do i será uma matriz exceto a linha i
e tudo que tiver abaixo e a linha i será outra matriz, isso para dividir metade


In [1]:
import numpy as np 

x = np.arange(24).reshape(4,6) ## 4*6 = 24
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
x1 ,x2 = np.vsplit(x,[2])
print(x1,'\n')
print(x2,'\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 



## também podemos dividir em partes iguais usando a sintaxe
# split(x,4) para dividir em 4 partes iguais;

In [4]:
x1 ,x2,x3,x4 = np.vsplit(x,4)
print(x1,'\n')
print(x2,'\n')
print(x3,'\n')
print(x4,'\n')

[[0 1 2 3 4 5]] 

[[ 6  7  8  9 10 11]] 

[[12 13 14 15 16 17]] 

[[18 19 20 21 22 23]] 

