## Trabalhando com reshape em vetores 3D
# muito util em ML para manipular a base de dados

In [1]:
import numpy as np

In [3]:
x = np.random.randint(100,size=(3,3))
print(x)


[[[ 0 81 73]
  [89 34 17]
  [64 56 20]]]
