## Trabalhando com reshape em vetores 3D
# muito util em ML para manipular a base de dados

In [1]:
import numpy as np

In [4]:
x = np.random.randint(100,size=(3,3))
print(x)


[[38 98  4]
 [47 34 20]
 [36 16 90]]


In [6]:
## nessa estrutura temos um erro pq a os valores não sao igauis
# temos que 3 x 3 = 9 
# então (1 x 2 x 2) também tem que ser igual a 9
x1 = x.reshape(1,2,2)
print(x)

ValueError: cannot reshape array of size 9 into shape (1,2,2)

In [9]:
## Estrutura possivel
# temos que 3 x 3 = 9 
# então (1 x 3 x 3) também tem que ser igual a 9
x1 = x.reshape(1,3,3)
print(x1)

[[[38 98  4]
  [47 34 20]
  [36 16 90]]]


In [10]:
x = np.random.randint(100,size=(3,4))
print(x)


[[62 95 34 74]
 [ 5 37 15 66]
 [35 28 12 15]]


In [12]:
x1 = x.reshape(2,2,3)
print(x1)

[[[62 95 34]
  [74  5 37]]

 [[15 66 35]
  [28 12 15]]]


In [16]:
x1 = x.reshape(3,1,4)
print(x1)

[[[62 95 34 74]]

 [[ 5 37 15 66]]

 [[35 28 12 15]]]
