## trabalhando com slicing ou fatiamento em vetores 3D

In [4]:
import numpy as np
x = np.random.randint(100,size=(9,3)).reshape(3,3,3)
print(x)


[[[56 12 43]
  [64 83 59]
  [42 66 64]]

 [[78 50 77]
  [10 49 51]
  [76 29 84]]

 [[25 77 99]
  [22 55 65]
  [31 35  1]]]


In [16]:
## pegando apenas a ultima matriz
m2_n = x[-1:,0:,0:]

print(m2_n)


## pegando apenas a ultima matriz
m2_n = x[3:,0:,0:]
print(m2_n)

[[[25 77 99]
  [22 55 65]
  [31 35  1]]]
[]


In [23]:
## obtendo apenas os 2 ultimos elementos de todas as primeiros colunas
m2_n = x[0:,0:,:1]
print(m2_n)


print("\n Outra forma de fazer\n ")
## obtendo apenas os 2 ultimos elementos de todas as primeiros colunas
m2_n = x[0:,:3,:1]
print(m2_n)

[[[56]
  [64]
  [42]]

 [[78]
  [10]
  [76]]

 [[25]
  [22]
  [31]]]

 Outra forma de fazer
 
[[[56]
  [64]
  [42]]

 [[78]
  [10]
  [76]]

 [[25]
  [22]
  [31]]]
