## Trabalhando com vetores 3D

# vetores 3D são empilhamento de matrizes

In [1]:
import numpy as np

In [3]:
## vetor normal 1D
v1 = np.array( [ 1,2,3 ] )

## vetor 2D ou matriz
v2 = np.array( [ [ 1,2,3 ] ] )

## vetor 3D lista de matrizes
v3 = np.array( [ [ [ 1,2,3 ] ]  ])

In [5]:
print("V1: ")
print(v1)
print(v1.shape,'\n') ## vetor com 3 elementos

print("V2: ")
print(v2)
print(v2.shape,'\n') ## matriz com 1 linha e 3 colunas


print("V3: ")
print(v3)
print(v3.shape,'\n') ## Vetor 3D com uma camada e contendo uma matriz [1,3]

V1: 
[1 2 3]
(3,) 

V2: 
[[1 2 3]]
(1, 3) 

V3: 
[[[1 2 3]]]
(1, 1, 3) 



In [8]:
## Criando um vetor 3D de 1 camada e uma matrizes [3,3]
v = np.array( [ [ [ 1,2,3 ], [ 1,2,3 ],[ 1,2,3 ] ]  ])

print(v)
print(v.shape,'\n')

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
(1, 3, 3) 



In [10]:
## Criando um vetor 3D de 2 camada onde cada camada contem uma matrizes [2,2]
v = np.array( [ [ [ 1,2 ], [ 1,2] ] , [ [ 1,2 ],[ 1,2 ]]  ])

print(v)
print(v.shape,'\n')

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]
(2, 2, 2) 

