# removendo elementos nuloes

In [2]:
import numpy as np
x = np.array([ 1,0,2,0,np.nan,0,3,np.nan,5,0])
x

array([ 1.,  0.,  2.,  0., nan,  0.,  3., nan,  5.,  0.])

In [11]:
print(x.nonzero())
print("tupla", type(x.nonzero()))
indices = x.nonzero()
print("Diferentes formas: ")
print(x[indices])
print(x[x.nonzero()])

print("removendo zeros e NaN")
retorno = x[indices][~np.isnan(x[indices])]
print(retorno)

(array([0, 2, 4, 6, 7, 8]),)
tupla <class 'tuple'>
Diferentes formas: 
[ 1.  2. nan  3. nan  5.]
[ 1.  2. nan  3. nan  5.]
removendo zeros e NaN
[1. 2. 3. 5.]
