#criando funcao para remover infinito e definindo posicao

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,0,5])
r = a/b
r

/tmp/ipykernel_59658/2959122870.py:4: RuntimeWarning: divide by zero encountered in divide
  r = a/b


array([ 1.,  1.,  1., inf,  1.])

In [4]:
def remove_inf_pos(x):
    pi = np.where( x == np.inf) ## indices dos infinitos
    i = np.where( x != np.inf) ## indices dos não infinitos
    return x[i],pi

In [5]:
remove_inf_pos(r) ## retorna duas tupla de acordo com os retornos


(array([1., 1., 1., 1.]), (array([3]),))

# (array([1., 1., 1., 1.]), (array([3]),))

# o retorno como todo é uma tupla (array([1., 1., 1., 1.]), (array([3]),))
# dentro dela temos uma  array([1., 1., 1., 1.]) como primeiro elemento
# temos uma tupla como segundo elemento (array([3]),) e dentro dela um array como elemento



In [8]:
c1,pinf = remove_inf_pos(r)  ##dividindo

print(c1)
print(pinf)

print('-----------')
print('aceesando elemento da tupla')
pinf[0]

[1. 1. 1. 1.]
(array([3]),)
-----------
aceesando elemento da tupla


array([3])