##Transformando Array -> list
##transformando List -> list

In [7]:
import numpy as np
r = np.arange(0,9)

r

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## ARRAY -> LIST

In [8]:
#precisa atribuir para modficiar
r = r.tolist()
r

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
#precisa não atribuir para modficiar
r = np.arange(0,9)
list(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

LIST -> ARRAY

In [16]:
r = np.array(r)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
r = list(r)
r



[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [38]:
## só altera se for atribuido
np.asarray(r)
r

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [40]:
r = np.asarray(r)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8])