#vetor arange() para gerar sequencias de numero

In [1]:
import numpy as np 

x = np.array([0,1,2,-4,-3,-2,-1,3,4,5])

In [3]:
#gerarndo numeros de 0 - 9 

a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
#gerarndo numeros de 1 - 9 

a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# gerando de 50 - 100 pulando de 2 em 2

a = np.arange(1,101,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])