##Trabalhando com arrays especiais 
# zeros, empty e Ones

In [1]:
import numpy as np 

x = np.array([0,1,2,-4,-3,-2,-1,3,4,5])

In [14]:
#preenche um vetor com varios zeros
u = np.zeros(20) ## 20 posicoes de zero
u

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [17]:
## cria 20 posicoes vazias
u = np.empty(20)
u

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [16]:
## criando vetor identidade
z = np.ones(20)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])