## usando metodos repeat() e full()

In [1]:
import numpy as np 

x = np.array([0,1,2,-4,-3,-2,-1,3,4,5])

In [4]:
h = np.array([0])
print(h)

h.repeat(20)

[0]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## utilizando a funcao .full() 

# muito uteis em arrays de multiplas dimenssoes

In [13]:
z = np.array([0,1,2,-4,-3,-2,-1,3,4,5])


#preenchendo do 1 ao 9 de numeros 7
q = np.full((1,9),7)

q

array([[7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [14]:
u = np.ones(9)*7
print(u)

print(q.dtype)
print(z.dtype)

[7. 7. 7. 7. 7. 7. 7. 7. 7.]
int64
int64


## funcao .full possibilita a expansão do vetor

# por isso  [[ ]] ou array([[7, 7, 7, 7, 7, 7, 7, 7, 7]]) 
# diferente de [7. 7. 7. 7. 7. 7. 7. 7. 7.]
# além de um ser inteiro e outro float


In [16]:
print("shape u: ", u.shape) # um linha com nome elementos
print("shape q", q.shape)# uma linha com 9 colunas 

shape u:  (9,)
shape q (1, 9)


In [19]:
q2 = np.full((2,9),7)

print(q2)
print(q2.shape)

[[7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]]
(2, 9)
