##Exercicio 01 - avaliar a igualdade de vetores e seus elementos

* a partir de dois vetores x e y;
* construir uma função/alg para avaliar se dois vetores são iguais ou diferentes;
* apresentar os elementos iguais dos vetores;
* comparar elemento por elemento dos vetores apresentar indices onde os valores são iguais nos dois vetores

In [1]:
import numpy as np

In [2]:
x = np.array([1.0,3.,2.6,4.3,7.7,5.6])
y = np.array([1.,2.6,3.,4,7,5.6])

In [3]:
def todosIguais(cmp):
    return cmp.all()


In [16]:
def verificaIguais(x,y):
    iguaisIndices = np.where(x == y)
    result = map(lambda indice:f' indice {indice} de valor {y[indice]}',iguaisIndices)
    print(list(result))



In [17]:
vetor_cmp = x == y
print("vetor comparação entre os veltores: ",vetor_cmp)

if(todosIguais(vetor_cmp)):
    print("todos os vetores são iguais")
    verificaIguais(x,y)
else:
    if(vetor_cmp.any()):
        print("existe alguns indices semelhantes")
        verificaIguais(x,y)

    else:
        print("todos os vetores são diferentes")

vetor comparação entre os veltores:  [ True False False False False  True]
existe alguns indices semelhantes
[' indice [0 5] de valor [1.  5.6]']


# Resolução do material

In [18]:
cmp = x == y

i = 0 

if(cmp.all()):
    print("Todos os elementos são iguais")
elif(cmp.any()):

    print("Alguns elementos são iguais, são eles:")

    for e in cmp:
        if(e):
            print("%.1f"%x[i])
        i += 1
    print('--------------------')    

    for e in x:
        j = np.where( e == y)
        print(j)
        if(j[0].size !=0):
            print(y[j])

else:
    print("Todos os elementos são diferentes.")


Alguns elementos são iguais, são eles:
1.0
5.6
--------------------
(array([0]),)
[1.]
(array([2]),)
[3.]
(array([1]),)
[2.6]
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5]),)
[5.6]
