## Trabalhando com transformações de Array 3D

In [1]:
import numpy as np
x = np.random.randint(100,size=(9,3)).reshape(3,3,3)
print(x)


[[[57 59 30]
  [ 9 96 51]
  [93 40 41]]

 [[65 63 71]
  [13 54 75]
  [32 81 35]]

 [[26 35 54]
  [65 31 34]
  [50 48 54]]]


In [4]:
#utilizando reshape 3 * 3 * 3 = 27
# temos então reshape ṕara -> 2D que precisa  dar 27

x1 = x.reshape(9,3)
print(x1)

[[57 59 30]
 [ 9 96 51]
 [93 40 41]
 [65 63 71]
 [13 54 75]
 [32 81 35]
 [26 35 54]
 [65 31 34]
 [50 48 54]]


In [6]:
x2 = np.reshape(x, (9,3))
x2

array([[57, 59, 30],
       [ 9, 96, 51],
       [93, 40, 41],
       [65, 63, 71],
       [13, 54, 75],
       [32, 81, 35],
       [26, 35, 54],
       [65, 31, 34],
       [50, 48, 54]])