## Trabalhando com estatistica descritiva

# valor min, valor max, média e padrao

In [2]:
import numpy as np
x = np.random.randint(100,size=(9,3)).reshape(3,3,3)
print(x)

[[[36 90 24]
  [37 29 52]
  [58 80  3]]

 [[71 59  3]
  [69 63 75]
  [ 5 84 13]]

 [[24  4 81]
  [82 38 56]
  [75 64 17]]]


## Min, max, medio e padrao total

In [4]:
print("minimo total:",np.min(x))
print("max total:",np.max(x))
print("média total:",np.mean(x))
print("desvio padrao total:",np.std(x))

minimo total: 3
max total: 90
média total: 47.851851851851855
desvio padrao total: 28.17761615407166


## Também é possivel fazer resultadno dos vetores 3D

In [10]:
print("minimo Vetores:\n",np.min(x,axis=0))

minimo Vetores:
 [[24  4  3]
 [37 29 52]
 [ 5 64  3]]


In [9]:
print("max Vetores:\n",np.max(x,axis=0))

max Vetores:
 [[71 90 81]
 [82 63 75]
 [75 84 17]]


In [8]:
print("mean Vetores:\n",np.mean(x,axis=0))

mean Vetores:
 [[43.66666667 51.         36.        ]
 [62.66666667 43.33333333 61.        ]
 [46.         76.         11.        ]]
