## Trabalhando com funcoes especiais em vetores 3D

In [4]:
import numpy as np
x = np.random.randint(100,size=(3,9))
print(x)

x = x.reshape(3,3,3)
print(x)

[[69 66  7 41 11 34 34 57 31]
 [39 81 47 28 99 56  0 65 97]
 [ 4 79 95  7 63 44 30 46 47]]
[[[69 66  7]
  [41 11 34]
  [34 57 31]]

 [[39 81 47]
  [28 99 56]
  [ 0 65 97]]

 [[ 4 79 95]
  [ 7 63 44]
  [30 46 47]]]


In [7]:
## vetor cheio de 1
a = np.ones((3,3,3));a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
b = np.zeros((3,3,3));b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### matriz identidade é sempre simetrico, por isso um 3,3,3 não existe

In [9]:
c = np.eye((3,3,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [13]:
c = np.eye((4));c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])