## Somatório e tipos de somátorios entre os membros

In [1]:
import numpy as np
x = np.random.randint(100,size=(9,3)).reshape(3,3,3)
print(x)

[[[ 3 29 94]
  [34 97 70]
  [13 25 82]]

 [[58 58 20]
  [11 90 38]
  [22 11 88]]

 [[27 82 55]
  [59 79 40]
  [70 21 54]]]


In [2]:
## soma de todos os elementos de uma matriz

x.sum()

1330

In [3]:
## matriz resultado da soma de x[0] + v[1] + v[3]
# importante notar a escolha do eixo que a soma acontecerá

x1  = np.sum(x,axis=0)
x1

array([[ 88, 169, 169],
       [104, 266, 148],
       [105,  57, 224]])

In [4]:

x2  = np.sum(x,axis=0)
x2

array([[ 88, 169, 169],
       [104, 266, 148],
       [105,  57, 224]])