## utilizando os metodos load,loadtxt 

# np.loadtxt('filename',dtype=tipo da leitura)

In [1]:
import numpy as np

In [3]:
u = np.loadtxt('dados.txt',dtype=int);u

array([[ 8, 21],
       [10, 16]])

In [4]:
u = np.loadtxt('dados.txt',dtype=float);u

array([[ 8., 21.],
       [10., 16.]])

## se ler com o formato inferior ao salvo da erro

In [7]:
## dados1.txt foi salvo como FLOAT
u = np.loadtxt('dados1.txt',dtype=int);u

/tmp/ipykernel_55568/2010571773.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  u = np.loadtxt('dados1.txt',dtype=int);u


array([1, 2, 3, 4])

In [8]:
u = np.loadtxt('dados1.txt',dtype=float);u

array([1.2, 2. , 3.2, 4.3])