## aprendendo a utilizar os metodos .tofile() e fromfile() 

In [2]:
import numpy as np

x = np.array([1,2,3,4]);x

array([1, 2, 3, 4])

### utilizando tofile para ciar um txt dos elementos de X separados por ; no formato string

# array.tofile('filename','separador',format=tipo da variavel)

In [5]:
x.tofile('tofile.txt',';',format='%s')

In [6]:
## criando um CSV
x.tofile('tofile.csv',';',format='%s')

## trabalhando com fromfile()

# numpy.fromfile(file, dtype=float, count=-1, sep='', offset=0, *, like=None)

In [27]:
#lendo o Txt criado
y = np.fromfile('tofile.txt',dtype=np.int32,count=3,sep=';',offset=0,like=None);y

array([1, 2, 3], dtype=int32)

In [28]:
## lendo diferentes indices:

y = np.fromfile('tofile.txt',dtype=np.int32,count=2,sep=';',offset=0,like=None);y

array([1, 2], dtype=int32)

In [30]:

## da erro com formato diferente
y = np.fromfile('tofile.txt',dtype=np.str_,count=3,sep=';',offset=0,like=None);y

array(['', '', ''], dtype='<U0')