##Fatiando vetores

#utilizando list comprehension para criar matrizes


In [1]:
import numpy as np

In [10]:
vetor = [1,2,3,4]
list = [range(i - 1,i+4) for i in vetor]

# liste é um array de ranges seguindo a logica acima
# cada range desse irá criar uma linha
list

[range(0, 5), range(1, 6), range(2, 7), range(3, 8)]

In [14]:

##dois jeitos são possiveis 
x = np.array(list)
print(x)
print("------------------------")


x = np.array([range(i - 1,i+4) for i in vetor])
print(x)
print("------------------------")
print("shape: ", x.shape)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
------------------------
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
------------------------
shape:  (4, 5)


## utilizando conceitos de slicing

In [20]:
#coletando a linha 1
print(x[1,:])


print("#coletando a linha 3: ",x[2,:])
print("#coletando a coluna 3: ",x[:,2])

##criando subMatrzies
print("------------------------")
print("tudo que tem depois da linha 3 e tudo que tem depois da coluna 4")
print("sub matriz de x: ",x[2:,3:])

[1 2 3 4 5]
#coletando a linha 3:  [2 3 4 5 6]
#coletando a coluna 3:  [2 3 4 5]
------------------------
tudo que tem depois da linha 3 e tudo que tem depois da coluna 3
sub matriz de x:  [[5 6]
 [6 7]]
