##utilizando os conceitos de slicing para criar submatrizes

In [8]:
import numpy as np
vetor = [1,2,3,4]
x = np.array([range(i - 1,i+4) for i in vetor])
x

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [14]:
## obtendo a meiuca das matriz principal
##pegando região da linha 2 até a coluna 4
y = x[1:3,1:4] ## lembrando sempre que os index pega sempre uma anterior
#sendo assim para pegar apatir da linha 2 ( index 1) 

y #pegando só a meiuca

array([[2, 3, 4],
       [3, 4, 5]])

In [19]:
##excluindo a primeira coluna e a ultima coluna

h = x[:,1:4]
h


h = x[:,2:4]
h

# só a ultima
h = x[:,3:4]
h

array([[3],
       [4],
       [5],
       [6]])