##Fatiando vetores

#utilizando list comprehension para criar matrizes


In [1]:
import numpy as np

In [10]:
vetor = [1,2,3,4]
list = [range(i - 1,i+4) for i in vetor]

# liste é um array de ranges seguindo a logica acima
# cada range desse irá criar uma linha
list

[range(0, 5), range(1, 6), range(2, 7), range(3, 8)]

In [13]:

##dois jeitos são possiveis 
x = np.array(list)
print(x)
print("------------------------")


x = np.array([range(i - 1,i+4) for i in vetor])
print(x)
print("------------------------")


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
------------------------
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
------------------------
