## trabalhando com vetores 2D

In [3]:
import numpy as np

#representando vetor 2D
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
##representando a transposta
x.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## modificando valores de matrizes

In [5]:
y = x.T

## Utilizando slice para modificar vetores

## utilizando broadcasting em numpy, qunado um valor é propagado para outro

In [13]:
## modificando o valhor 8 da matriz para 10
## posicao linha 4, coluna 2
y = x.T

print("shape: ",y.shape)
print("----------------------")

y[3,1]= 10
print("Matriz y:",y)
print("----------------------")
print("Matriz x:",x)

#note que alterando o valor de y também alteramos os valores de x 

shape:  (4, 2)
----------------------
Matriz y: [[ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4 10]]
----------------------
Matriz x: [[ 1  2  3  4]
 [ 5  6  7 10]]


## resolvendo problema de broadcasting