##Matrizes importantes

In [2]:
import numpy as np 

## comando cria uma matrizes identidade onde podemos setar os valores da diagonal principal
x = np.diagflat([3,4]) 
x

array([[3, 0],
       [0, 4]])

In [3]:
x = np.diagflat([3,4,5]) 
x

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [4]:
x = np.diagflat([3,4,5,6]) 
x

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

## coletando os valores da diagonal principal com o comando:
#.diag



In [5]:
d = np.diag(x)

d

array([3, 4, 5, 6])

## Realizando a soma da diagonal principal
# também chamado de - TRAÇO -

In [6]:
trace = np.trace(x)

trace

18