##MAtrizes especiais

In [2]:
## funcao empty criando matrizes de zeros ou vazias

import numpy as np 

x = np.empty((5,4)) ## os numeros não são zeros mas são extramente pequenos, na pratica vazio
x

array([[2.23505970e-316, 0.00000000e+000, 2.40677185e-239,
        3.23136435e-234],
       [1.45272632e-296, 1.57730203e-234, 7.88786248e-297,
        7.93529732e-301],
       [2.49821039e-306, 6.01293950e-215, 9.53035071e-292,
        9.34035634e-181],
       [1.07280287e-296, 1.56812224e-248, 5.13373934e-307,
        5.34045567e-307],
       [3.02009204e-282, 2.78288555e-307, 1.60294408e-306,
        9.99035900e-311]])

In [3]:
x = np.zeros((5,4)) ## os numeros não são zeros mas são extramente pequenos, na pratica vazio
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##Criando matriz identidade

In [6]:
x = np.eye(4)
print(x)

x = np.eye(3)
print("--------------------")
print(x)

x = np.eye(2)
print("--------------------")
print(x)

x = np.eye(5)
print("--------------------")
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[1. 0.]
 [0. 1.]]
--------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
