## usando a funcao clip()

In [5]:
import numpy as np 

x = np.array([-4,-3,-2,-1,0,1,2,3,4,5])

In [9]:
#igualando os extremos para 2 

x.clip(-2,2)

print(x)

## cria um intervalo, todos abaixo de 2 viram -2 todos acima de 2 viram 2
## os do meio n sofrem alteração
x = x.clip(-2,2)
print(x)

[-4 -3 -2 -1  0  1  2  3  4  5]
[-2 -2 -2 -1  0  1  2  2  2  2]


In [10]:
x = np.array([-4,-3,-2,-1,0,1,2,3,4,5])
x = x.clip(0,4)
print(x)

[0 0 0 0 0 1 2 3 4 4]
